---
stages:
  build_features:
    cmd:
      - >-
        python ./scripts/data/build_features.py.py
        --input-rumbles-dir "./data/01_raw/cornell_data/Rumble/"
        --output-dir "./data/02_features/rumbles/spectrograms_test2"
        --duration 60.0
        --freq-min 0.0
        --freq-max 250.0
        --random-seed 0
        --ratio-random-offsets 0.2
        --loglevel "info"
    deps:
      - ./scripts/data/build_features.py
    outs:
      - ./data/02_features/rumbles/spectrograms_test2/
