---
stages:
  build_features:
    cmd:
      - >-
        python ./scripts/data/build_features.py
        --input-rumbles-dir "./data/01_raw/cornell_data/Rumble/"
        --output-dir "./data/02_features/rumbles/spectrograms/"
        --duration 60.0
        --freq-min 0.0
        --freq-max 250.0
        --random-seed 0
        --ratio-random-offsets 0.2
        --loglevel "info"
    deps:
      - ./scripts/data/build_features.py
    outs:
      - ./data/02_features/rumbles/spectrograms/
  build_yolov8_model_input_small:
    cmd:
      - >-
        python ./scripts/data/build_yolov8_model_input.py
        --input-features "./data/02_features/rumbles/spectrograms/"
        --output-dir "./data/03_model_input/yolov8/small/"
        --ratio 0.01
        --ratio-train-val 0.8
        --loglevel "info"
    deps:
      - ./scripts/data/build_yolov8_model_input.py
      - ./data/02_features/rumbles/spectrograms/
    outs:
      - ./data/03_model_input/yolov8/small/
  build_yolov8_model_input_full:
    cmd:
      - >-
        python ./scripts/data/build_yolov8_model_input.py
        --input-features "./data/02_features/rumbles/spectrograms/"
        --output-dir "./data/03_model_input/yolov8/full/"
        --ratio 1.0
        --ratio-train-val 0.8
        --loglevel "info"
    deps:
      - ./scripts/data/build_yolov8_model_input.py
      - ./data/02_features/rumbles/spectrograms/
    outs:
      - ./data/03_model_input/yolov8/full/
  # train_yolov8_baseline_small_dataset:
  #   cmd:
  #     - >-
  #       python ./scripts/model/yolov8/train.py
  #       --data ./data/03_model_input/yolov8/small/data.yaml
  #       --config ./scripts/model/yolov8/configs/baseline.yaml
  #       --experiment-name baseline_small_dataset
  #       --loglevel info
  #   deps:
  #     - ./scripts/model/yolov8/train.py
  #     - ./scripts/model/yolov8/configs/baseline.yaml
  #     - ./data/03_model_input/yolov8/small/
  #   outs:
  #     - ./data/04_models/yolov8/baseline_small_dataset/
